Check whether action value is string before calling format()
AttributeError: 'int' object has no attribute 'format' will be raised
if we pass an integer value, so we should check whether the value is
a string or not.

Change-Id: I14ed4d404a9be1233493083bef49218cf0f45867
Closes-Bug: #1608393