Use my_ip as default URL instead of localhost
python-openstackclient for ironic-discoverd fails like:
 $ openstack baremetal introspection status <uuid>
 ERROR: openstack 'utf8' codec can't decode byte 0xa5 in position 89:
 invalid start byte

When set "DISCOVERD_URL" environment value as http://<my_ip>:5050,
this error doesn't occur.
So that, the reason of this error is using localhost as default url.

This patch set fix the default url to host's URL.

Change-Id: I59e6bf30c19eee65b52e8d2bd56c148cd3b29efa
Closes-Bug: #1439468