Update requirements
Update minimum required versions of python packages.
The updates is based on crosscheck requirements from required
packages:

oslo-policy 3.7.0 depends on oslo.context>=2.22.0

increase oslo-service version to be able to use eventlet 0.26.0
oslo-service 1.24.0 depends on eventlet!=0.18.3, !=0.20.1, <0.21.0 and >=0.18.2

increase oslo-log version to fix error:
AttributeError: type object 'deprecated' has no attribute 'WALLABY'

oslo-log 4.3.0 depends on oslo.serialization>=2.25.0
oslo-log 4.3.0 depends on pbr>=3.1.1
oslo-log 4.3.0 depends on oslo.i18n>=3.20.0

Change-Id: I20a5a20b94ffd27ea34f23ac89ca2826eb548b1a