Stringify node_info.uuid as a precaution
Currently, utils:processing_logger_prefix() assumes node_info.uuid to be a
string.  However, a (broken) test case could encounter a TypeError logging:

   File "ironic_inspector/utils.py", line 103, in processing_logger_prefix
     return _('[node: %s]') % ' '.join(parts)
 TypeError: sequence item 0: expected string, MagicMock found

The patch purpose is to apply str(node_info.uuid) as a precaution.  This may
also help track where the real issue is with a broken test case.

Change-Id: I689f67c44a6304f7b296829fef3339872a4f6d36